export type {
  Infer,
  ParseFail,
  ParseMode,
  ParseOk,
  ParseOptions,
  ParseResult,
  RefineIssue,
  Schema,
  SuperRefineContext,
} from "./core";
export {
  type FormatValidationErrorOptions,
  formatValidationError,
  type Path,
  ValidationError,
  type ValidationIssue,
} from "./errors";
export type { OpenApiSchemaObject } from "./openapi";
export { toOpenApi } from "./openapi";

import {
  type ArrayOptions,
  array,
  type BooleanOptions,
  boolean,
  type DateOptions,
  type DateStringOptions,
  type DateTimeStringOptions,
  date,
  dateString,
  dateTimeString,
  defaultValue,
  enumSchema,
  literal,
  type NumberOptions,
  nullable,
  number,
  type ObjectOptions,
  object,
  objectOf,
  optional,
  record,
  registerStringValidator,
  type SchemaShape,
  type StringCustomValidatorFn,
  type StringCustomValidatorInput,
  type StringCustomValidatorResult,
  type StringOptions,
  string,
  tuple,
  type UnionOptions,
  union,
} from "./builders";
import type { Infer, Schema } from "./core";

export const s = {
  string,
  registerStringValidator,
  number,
  boolean,
  date,
  dateString,
  dateTimeString,
  literal,
  array,
  tuple,
  object,
  objectOf,
  record,
  optional,
  nullable,
  default: defaultValue,
  enum: enumSchema,
  union,
};

export type {
  ArrayOptions,
  BooleanOptions,
  DateOptions,
  DateStringOptions,
  DateTimeStringOptions,
  NumberOptions,
  ObjectOptions,
  SchemaShape,
  StringCustomValidatorFn,
  StringCustomValidatorInput,
  StringCustomValidatorResult,
  StringOptions,
  UnionOptions,
};
export {
  array,
  boolean,
  date,
  dateString,
  dateTimeString,
  defaultValue as default,
  enumSchema as enum,
  literal,
  nullable,
  number,
  object,
  objectOf,
  optional,
  record,
  registerStringValidator,
  string,
  tuple,
  union,
};

export type InferObject<T extends Record<string, Schema<unknown>>> = {
  [K in keyof T]: Infer<T[K]>;
};
