services:
  app:
    init: true
    security_opt:
      - no-new-privileges:true
    build:
      context: ../..
      dockerfile: apps/app-starter/Dockerfile
    environment:
      ENV: production
    restart: unless-stopped
